"""baseline schema rev 0.1 - 14 tables (QMS-011 / worklog 0001).

Single baseline migration: creates the whole physical schema described in
`docs/architecture.md` section 5 (8 core tables + 6 reference tables).
Applies to an empty DB with `alembic upgrade head` and rolls back cleanly
with `alembic downgrade base`.

Revision ID: baseline
Revises: 
Create Date: 2026-08-11 09:48:12.954985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characteristic_group',
    sa.Column('cg_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('cg_id', name=op.f('pk_characteristic_group')),
    sa.UniqueConstraint('name', name=op.f('uq_characteristic_group_name'))
    )
    op.create_table('ref_connection_type',
    sa.Column('connection_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('connection_type_id', name=op.f('pk_ref_connection_type')),
    sa.UniqueConstraint('name', name=op.f('uq_ref_connection_type_name'))
    )
    op.create_table('ref_deviation_type',
    sa.Column('deviation_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('deviation_type_id', name=op.f('pk_ref_deviation_type')),
    sa.UniqueConstraint('name', name=op.f('uq_ref_deviation_type_name'))
    )
    op.create_table('ref_inspection_type',
    sa.Column('inspection_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('inspection_type_id', name=op.f('pk_ref_inspection_type')),
    sa.UniqueConstraint('name', name=op.f('uq_ref_inspection_type_name'))
    )
    op.create_table('ref_item_type',
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('item_type_id', name=op.f('pk_ref_item_type')),
    sa.UniqueConstraint('name', name=op.f('uq_ref_item_type_name'))
    )
    op.create_table('ref_size',
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('size_id', name=op.f('pk_ref_size')),
    sa.UniqueConstraint('name', name=op.f('uq_ref_size_name'))
    )
    op.create_table('ref_zone',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('zone_id', name=op.f('pk_ref_zone')),
    sa.UniqueConstraint('name', name=op.f('uq_ref_zone_name'))
    )
    op.create_table('g_position',
    sa.Column('g_position_id', sa.Integer(), nullable=False),
    sa.Column('cg_id', sa.Integer(), nullable=False),
    sa.Column('g_index', sa.Integer(), nullable=False),
    sa.Column('nominal', sa.Float(), nullable=True),
    sa.Column('tol_plus', sa.Float(), nullable=True),
    sa.Column('tol_minus', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cg_id'], ['characteristic_group.cg_id'], name=op.f('fk_g_position_cg_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('g_position_id', name=op.f('pk_g_position')),
    sa.UniqueConstraint('cg_id', 'g_index', name='uq_g_position_cg_index')
    )
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_number', sa.String(length=64), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.Column('connection_type_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connection_type_id'], ['ref_connection_type.connection_type_id'], name=op.f('fk_item_connection_type_id')),
    sa.ForeignKeyConstraint(['item_type_id'], ['ref_item_type.item_type_id'], name=op.f('fk_item_item_type_id')),
    sa.ForeignKeyConstraint(['size_id'], ['ref_size.size_id'], name=op.f('fk_item_size_id')),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_item')),
    sa.UniqueConstraint('item_number', name=op.f('uq_item_item_number'))
    )
    op.create_table('characteristic',
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('local_number', sa.String(length=32), nullable=False),
    sa.Column('state_depending_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], name=op.f('fk_characteristic_item_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_depending_id'], ['characteristic.characteristic_id'], name=op.f('fk_characteristic_state_depending_id')),
    sa.PrimaryKeyConstraint('characteristic_id', name=op.f('pk_characteristic')),
    sa.UniqueConstraint('item_id', 'local_number', name='uq_characteristic_item_local')
    )
    op.create_table('deviation',
    sa.Column('deviation_id', sa.Integer(), nullable=False),
    sa.Column('dev_number', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('wo', sa.String(length=64), nullable=False),
    sa.Column('machine', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ncr', sa.String(length=64), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=False),
    sa.Column('decision_dev', sa.String(length=16), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('attachment', sa.Text(), nullable=True),
    sa.CheckConstraint("decision_dev IS NULL OR decision_dev IN ('approved', 'rejected', 'sorting', 'repair')", name=op.f('ck_deviation_decision_dev')),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], name=op.f('fk_deviation_item_id')),
    sa.PrimaryKeyConstraint('deviation_id', name=op.f('pk_deviation')),
    sa.UniqueConstraint('dev_number', name=op.f('uq_deviation_dev_number'))
    )
    op.create_table('finding',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('deviation_id', sa.Integer(), nullable=False),
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=1), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('dimension_point', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('deviation_type_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("direction IN ('+', '-')", name=op.f('ck_finding_direction')),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristic.characteristic_id'], name=op.f('fk_finding_characteristic_id')),
    sa.ForeignKeyConstraint(['deviation_id'], ['deviation.deviation_id'], name=op.f('fk_finding_deviation_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deviation_type_id'], ['ref_deviation_type.deviation_type_id'], name=op.f('fk_finding_deviation_type_id')),
    sa.ForeignKeyConstraint(['zone_id'], ['ref_zone.zone_id'], name=op.f('fk_finding_zone_id')),
    sa.PrimaryKeyConstraint('finding_id', name=op.f('pk_finding'))
    )
    op.create_table('mapping',
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.Column('g_position_id', sa.Integer(), nullable=True),
    sa.Column('is_absent', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(g_position_id IS NOT NULL AND is_absent = 0) OR (g_position_id IS NULL AND is_absent = 1)', name=op.f('ck_mapping_target_xor_absent')),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristic.characteristic_id'], name=op.f('fk_mapping_characteristic_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['g_position_id'], ['g_position.g_position_id'], name=op.f('fk_mapping_g_position_id')),
    sa.PrimaryKeyConstraint('mapping_id', name=op.f('pk_mapping')),
    sa.UniqueConstraint('characteristic_id', name=op.f('uq_mapping_characteristic_id'))
    )
    op.create_table('inspection',
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('insp_number', sa.String(length=20), nullable=False),
    sa.Column('deviation_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('decision_insp', sa.String(length=16), nullable=False),
    sa.Column('protocol', sa.Text(), nullable=False),
    sa.CheckConstraint("decision_insp IN ('approved', 'not_approved')", name=op.f('ck_inspection_decision_insp')),
    sa.ForeignKeyConstraint(['deviation_id'], ['deviation.deviation_id'], name=op.f('fk_inspection_deviation_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.finding_id'], name=op.f('fk_inspection_finding_id')),
    sa.ForeignKeyConstraint(['type_id'], ['ref_inspection_type.inspection_type_id'], name=op.f('fk_inspection_type_id')),
    sa.PrimaryKeyConstraint('inspection_id', name=op.f('pk_inspection')),
    sa.UniqueConstraint('insp_number', name=op.f('uq_inspection_insp_number'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspection')
    op.drop_table('mapping')
    op.drop_table('finding')
    op.drop_table('deviation')
    op.drop_table('characteristic')
    op.drop_table('item')
    op.drop_table('g_position')
    op.drop_table('ref_zone')
    op.drop_table('ref_size')
    op.drop_table('ref_item_type')
    op.drop_table('ref_inspection_type')
    op.drop_table('ref_deviation_type')
    op.drop_table('ref_connection_type')
    op.drop_table('characteristic_group')
    # ### end Alembic commands ###
